#ifndef MOTIONPLANNING_IDL
#define MOTIONPLANNING_IDL
#include "BasicDataType.idl"
#include "ExtendedDataTypes.idl"
module Planning
{
  const long OK=0;
  const long NG=-1;
  
  struct ManipPos{
    double rotation[9];
    double position[3];
  };
  
  typedef sequence<double> theta;

  interface MotionPlanningInterface
  {
    long MotionGenerate_Joint(in theta q_goal);
    long MotionGenerate(in ManipPos EEfPos);
  };
};
#endif //MOTIONPLANNING
